name: On Push Run

on: push

env:
  DEVOPS_DIR: ci-cd

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out ci-cd repository
      uses: actions/checkout@v2
      with:
        repository: krishnavarma0193/CI-CD
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/hello_world.py
      shell: sh
