name: On Push Run

on: push

env:
  DEVOPS_DIR: ci-cd

jobs:
  deployment-workflow:
    name: deployment-workflow
    runs-on: ubuntu-latest
    steps:
    - name: Check-out ci-cd repository
      uses: actions/checkout@v2
      with:
        repository: krishnavarma0193/CI-CD
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}
    
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
